apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: sample-web
  namespace: forgelab
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sample-web
                port:
                  name: http
